apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: github-runners
  name: github-runner-arm64
  labels:
    app: github-runner-arm64
spec:
  replicas: 4
  selector:
    matchLabels:
      app: github-runner-arm64
  template:
    metadata:
      labels:
        app: github-runner-arm64
    spec:
      nodeSelector:
        arch: arm64
      containers:
      - name: github-runner-arm64
        image: sebas:5000/github-runner:arm64-1
        securityContext:
          privileged: true
          runAsUser: 1000
        env:
        - name: GITHUB_OWNER
          value: koditoriet
        - name: ADDITIONAL_PACKAGES
          value: jq,podman,gcc,make,libsqlite3-dev
        - name: GITHUB_PAT
          valueFrom:
            secretKeyRef:
              name: registration-token
              key: pat

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: github-runners
  name: github-runner-amd64
  labels:
    app: github-runner-amd64
spec:
  replicas: 4
  selector:
    matchLabels:
      app: github-runner-amd64
  template:
    metadata:
      labels:
        app: github-runner-amd64
    spec:
      nodeSelector:
        arch: amd64
      containers:
      - name: github-runner-amd64
        image: sebas:5000/github-runner:amd64-1
        securityContext:
          privileged: true
          runAsUser: 1000
        env:
        - name: GITHUB_OWNER
          value: koditoriet
        - name: ADDITIONAL_PACKAGES
          value: jq,podman,swtpm,libtss2-dev,gcc,make,libsqlite3-dev,libdbus-1-dev
        - name: GITHUB_PAT
          valueFrom:
            secretKeyRef:
              name: registration-token
              key: pat
